// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package consent_manager

type AccessToken struct {
	ID           string `json:"id"`
	UUID         string `json:"uuid"`
	PatientID    string `json:"patientId"`
	PractionerID string `json:"practionerId"`
	Expiration   int    `json:"expiration"`
}

type ConsentEnforcement struct {
	ID           string   `json:"id"`
	Display      string   `json:"display"`
	UUID         string   `json:"uuid"`
	ReaderGroups []*Group `json:"readerGroups"`
	TargetGroups []*Group `json:"targetGroups"`
	Expiration   int      `json:"expiration"`
}

type Contract struct {
	ID           string   `json:"id"`
	Display      string   `json:"display"`
	UUID         string   `json:"uuid"`
	Clauses      []string `json:"clauses"`
	ReaderGroups []*Group `json:"readerGroups"`
	Hash         string   `json:"hash"`
}

type DataType struct {
	ID      string `json:"id"`
	Display string `json:"display"`
	UUID    string `json:"uuid"`
}

type Group struct {
	ID       string `json:"id"`
	Display  string `json:"display"`
	UUID     string `json:"uuid"`
	IsPublic bool   `json:"isPublic"`
}

type Patient struct {
	ID            string      `json:"id"`
	Display       string      `json:"display"`
	UUID          string      `json:"uuid"`
	PrivateKey    string      `json:"privateKey"`
	PublicKey     string      `json:"publicKey"`
	Groups        []*Group    `json:"groups"`
	DataTypes     []*DataType `json:"dataTypes"`
	RestorePhrase string      `json:"restorePhrase"`
	Passprase     string      `json:"passprase"`
}

type Practioner struct {
	ID            string   `json:"id"`
	Display       string   `json:"display"`
	UUID          string   `json:"uuid"`
	PrivateKey    string   `json:"privateKey"`
	PublicKey     string   `json:"publicKey"`
	Groups        []*Group `json:"groups"`
	RestorePhrase string   `json:"restorePhrase"`
	Passprase     string   `json:"passprase"`
}

type Signature struct {
	ID                   string `json:"id"`
	PatientID            string `json:"patientId"`
	ContractID           string `json:"contractId"`
	TargetGroup          string `json:"targetGroup"`
	Expiration           int    `json:"expiration"`
	ContractedSignedHash string `json:"contractedSignedHash"`
}
